### ISSUE TITLE
Should we fold the Summary model into filings?

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-campaign-browser#112]
Per a conversation I had with @armendariz, it may make sense to fold the `Summary` model into `Filing` since it's mostly aggregates and totals.

From what I can tell, outside of the mgmt commands to load and drop the db, the Summary model is only being used on the committee page to show some very basic information:

![summary](https://cloud.githubusercontent.com/assets/856628/4652052/81e15138-54a1-11e4-8eb5-f463b6607c2c.png)

^This is from this model property: https://github.com/california-civic-data-coalition/django-calaccess-campaign-browser/blob/master/calaccess_campaign_browser/models.py#L336

It's certainly helpful to have the `Summary` model to compare totals and make sure we're getting the correct data. So, maybe we could keep the model but I don't think we need to export it with the `exportcalaccesscampaignfinance` command. Thoughts?

**Comment by palewire** [comment]
I am marking this wontfix for the time being. We can always revisit it later.
