### ISSUE TITLE
document server deployment

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-campaign-browser#113]
- setup server with django, nginx, mysql, gunicorn
- possibly include an `install.sh` script to install all the dev tools required
- docs
- https://code.google.com/p/pypyodbc/wiki/Linux_ODBC_in_3_steps

**Comment by palewire** [comment]
I think we've got a good running start for this over at [the new bootstrap repository](https://github.com/california-civic-data-coalition/django-calaccess-bootstrap) so I'm going to close this and assume we'll continue this work over there.
