### ISSUE TITLE
AttributeError at /committee/5498/

### ISSUE THREAD

**Issue by kavyasukumar** [california-civic-data-coalition/django-calaccess-campaign-browser#131]

**Comment by aboutaaron** [comment]
Some pages are returning an `AttributeError` with the following: `NoneType does not have attribute _meta`

I imagine this has to do with some Committee objects not having a value or attriubute in the database. This may be solved by having something like this in the template:

```html
{% if object.attribute %}
  {{ object.attribute }}
{% endif %}
