### ISSUE TITLE
Did we figure out the issue with the expenditures table?

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-campaign-browser#176]
I remember during the code convening you (@palewire) mentioned we didn't have the Expenditure model table loaded because we were refactoring the model itself. Is this still the case?

**Comment by palewire** [comment]
The model we have is an early draft and, IMHO, needs a heavy rewrite before we do any serious analysis with it.

**Comment by aboutaaron** [comment]
Got it. Same with contributions then?

**Comment by aboutaaron** [comment]
I'm just trying to update SQL server here at CIR and I'm looking to figure out how to update some tables. No problem putting this on hold but the higher ups wanna know when I'm gonna update our database

**Comment by aboutaaron** [comment]
Rewriting this at the moment: https://github.com/california-civic-data-coalition/django-calaccess-campaign-browser/blob/master/calaccess_campaign_browser/management/commands/exportcalaccesscampaignbrowser.py

Too premature you think @palewire?

**Comment by palewire** [comment]
The contributions model and its field definitions is in much better shape, but we still have some work to do vetting our totals and making sure what we output is 100% correct. Looks at the expenditure model's field names and you'll see what I mean.

If you want an exporter, I say go ahead and do it. Though we really need people who know the system pouring the acid of doubt on our numbers.

**Comment by aboutaaron** [comment]
Well I can ignore expenditures now and focus on contributions. Though, the more I think about it, exporting the summary table would make more sense for high level summing right? Like, those values are more accurate than the itemized values anyway so we should just export that no?

—

**Comment by palewire** [comment]
Depends what you're after, but for big totals you're only allowed to used
the summaries.
