### ISSUE TITLE
Add Data Context

### ISSUE THREAD

**Issue by anabranch** [california-civic-data-coalition/django-calaccess-campaign-browser#185]
One of the things that I think is so hard about working with this data is understanding what I am working with. 

I feel it would really help contributions if you could understand what exactly this data represents and what kinds of questions can and can't be answered with it. The column names and tables are so arcane that any lay developer needs a ton of expertise/time to be able to get their hands dirty with working with this data.

It'd be great to have a journalist/someone with writing skill add this sort of information into the documentation. What is this data, what does it mean, what does it show?

**Comment by palewire** [comment]
You are 100% right, and the goal is to get there. However we're still in the process of untangling the dozens of tables and forms in the system. We have to figure it out before we can document it! 

That's going to be a slow, forensic process and we need all the help we can get. 

Right now we have routines that extract and transform the "filers" who put in campaign paperwork two kinds of their filings (Quarterly disclosures and late disclosures) with their summary totals, and line-item contributions disclosed on those same forms. 

Each of those routines should only be considered a draft, and we need people to invest time vetting and improving them. And after that there's a whole hell of a lot more data to go get (expenditures, "independent spending," major donor forms, etc).

Once we develop the expertise necessary to bless our code as fully accurate, then we're ready to start writing docs and telling other people how to do it.

**Comment by palewire** [comment]
Since this is such a large overarching mission of the project rather than a specific task I'm going to close the ticket, but it is a very crucial goal you can see reflected in many of the other tickets.

**Comment by anabranch** [comment]
Yup, makes sense. Just wanted to have a conversation about it!
