### ISSUE TITLE
Error loading data, Contributor Address is null

### ISSUE THREAD

**Issue by anabranch** [california-civic-data-coalition/django-calaccess-campaign-browser#186]
```sh
Loading contributions
 Quarterly filings
  Marking duplicates
   Dumping CSV sorted by unique identifier
   Marking duplicates in a new CSV
  Loading CSV
  Merging CSV data with other tables
  ...
django.db.utils.IntegrityError: (1048, "Column 'contributor_address_1' cannot be null")
```

https://github.com/california-civic-data-coalition/django-calaccess-campaign-browser/blob/master/calaccess_campaign_browser/models.py#L636

another relevant line:

https://github.com/california-civic-data-coalition/django-calaccess-campaign-browser/blob/master/calaccess_campaign_browser/management/commands/loadcalaccesscampaigncontributions.py#L706

**Comment by palewire** [comment]
Am I right to think this is the same bug [documented here](https://github.com/california-civic-data-coalition/django-calaccess-campaign-browser/issues/132)?

**Comment by anabranch** [comment]
Yeah I'd probably close this and assume it's part of the other one until I can prove otherwise.
