### ISSUE TITLE
Mozilla hack day code from front-end was removed

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-campaign-browser#193]
See #192

**Comment by palewire** [comment]
I parked it over in the ``frontend`` branch since some of the data pulls in the view weren't 100% right (They came from the line-item contributions, not the summary totals). We could articulate small tickets for each of the features that would repair those problems. Should I do that?

**Comment by aboutaaron** [comment]
That makes sense! Just making sure nothing got lost. Thanks!
