### ISSUE TITLE
can this app vend a REST api?

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-campaign-browser#209]
Does django provide an easy way to publish data via REST web services? If it did, that would be great. If not, would it make sense to suggest this as another project, as opposed to an issue in this one?

**Comment by palewire** [comment]
There are steps in this direction now with tastypie [here](https://github.com/california-civic-data-coalition/django-calaccess-campaign-browser/blob/master/calaccess_campaign_browser/urls.py#L9)

**Comment by aboutaaron** [comment]
FWIW, [Django REST Framework](https://github.com/tomchristie/django-rest-framework) seems to be the new darling for build REST APIs in Django. It even comes with a web interface a la the Django Admin to test queries.

I've historically used Django Tastypie for APIs but would probably use Django REST for new projects.
