### ISSUE TITLE
Watchdog 0.6.0 dependency fails on Mac OS X 10.9-10

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-campaign-browser#226]
Looks like a known problem: https://github.com/gorakhargosh/watchdog/issues/188

A fixed was merged here https://github.com/gorakhargosh/watchdog/pull/194 so perhaps it's worth bumping to a newer version?

@palewire are we using watchdog for a specific version reason or this a project dependency?

**Comment by aboutaaron** [comment]
Testing bumping to version 0.8.0 for fresh project bootstrap

**Comment by palewire** [comment]
I can't even remember. What are we using this for?

**Comment by aboutaaron** [comment]
I have no idea? I can pull the dependency but I'm actually unsure on what it does.
